### ISSUE TITLE
database breaks sometimes

### ISSUE THREAD

**Issue by sophec** [unixporn/trup#118]
read below for a bit of context

---

# Example:
`!note <mention> some stuff`

# Expected Behavior:
it works

# Actual Behavior:
it doesn't work

**Comment by eepykate** [comment]
@elkowar pretty sure you broke this one

**Comment by sophec** [comment]
I blame @elkowar for all of my problems now

**Comment by eepykate** [comment]
nevermind cactus broke it

@willeccles tell your friend he broke trup

someone got warned

then mod commands stopped working

**Comment by eepykate** [comment]
nevermind, it's all commands

**Comment by eepykate** [comment]
the user select thing works tho

**Comment by eepykate** [comment]
and so does !help

**Comment by eepykate** [comment]
and so does !role

**Comment by eepykate** [comment]
but fetch doesn't, and mute, warn, and note don't

**Comment by sophec** [comment]
literally nothing works and the world is burning around us

**Comment by eepykate** [comment]
this

**Comment by sophec** [comment]
see https://canary.discord.com/channels/635612648934735892/655947537538088962

**Comment by eepykate** [comment]
you're database is broke

**Comment by eepykate** [comment]
works: pfp, info, repo, move, delban, ban, poll, role, purge

not works: dotfiles, warn, blocklist (it still deletes, just the command is broken), fetch, setfetch (when you set, just `!setfetch` works), desc, note, mute

it still gives errors like "you must be a mod" and "not enough arguments", however when it actually tries to interact with the database it fails and doesn't do anything

**Comment by eepykate** [comment]
and for further context, cactus warned someone, then tried to add a note (within the minute) and the bot stopped working.

would be funny if the storage device is full lmao, just a tiny bit of text pushed it to the limit after the countless images it logged

**Comment by eepykate** [comment]
i did my detective work for today you're welcome

**Comment by sophec** [comment]
> 
> 
> you're database is broke

sorry you seem to have stolen cte's signature grammar:tm: so i am going to sue you now

**Comment by eepykate** [comment]
you may have a tiny cactus on your side, but i have a literal cactus on my side.

I will win this lawsuit, mark my words.

**Comment by sophec** [comment]
i also have a literal cactus his name is oscar

**Comment by eepykate** [comment]
oh ok

i have multiple

**Comment by eepykate** [comment]
What sort of a man would I be without proof?

![20201014_131539](https://user-images.githubusercontent.com/40295114/95939472-7be03b80-0e1f-11eb-8fb7-2cba9c55aa33.jpg)

**Comment by eepykate** [comment]
they also happen to be literal tiny cacti

nice

**Comment by eepykate** [comment]
![20201014_131915](https://user-images.githubusercontent.com/40295114/95939675-f610c000-0e1f-11eb-971f-2843779b80fe.jpg)

**Comment by sophec** [comment]
yeah but mine's named oscar

**Comment by eepykate** [comment]
good point

**Comment by buffet** [comment]
@6gk Images only get logges for 6 hours, my disk is doing fine.

**Comment by sophec** [comment]
only for 6 hours? brb making new issue

**Comment by elkowar** [comment]
> only for 6 hours? brb making new issue

it means that if an image gets deleted after more than 6 hours, it won't be logged. if an image stays for more than 6 hours, it's likely either fine, or the mod team wouldn't notice it anymore anyways...

**Comment by sophec** [comment]
oh idc then

**Comment by eepykate** [comment]
it has happened again twice since this issue was made.

**Comment by mlvzk** [comment]
@buffet logs plz

**Comment by eepykate** [comment]
and give someone ssh so they can fix stuff

@mlvzk 

![image](https://user-images.githubusercontent.com/40295114/96060761-bbb52a80-0ed4-11eb-8af6-853b723b425f.png)

**Comment by elkowar** [comment]
So what we gather from this is that golangs error handling is not only tedious to the point of unusability, but also absolutely worthless? Ig a rewrite would really benefit us quite a lot

**Comment by eepykate** [comment]
@buffet because i didn't do it earlier, here is a pie.

3.1415926535897932384626433832795028841971693993751058209749445923078164062862
089986280348253421170679821480865132823066470938446095505822317253594081284811
174502841027019385211055596446229489549303819644288109756659334461284756482337
867831652712019091456485669234603486104543266482133936072602491412737245870066

was that too much pie? share it with some friends i guess.

**Comment by eepykate** [comment]
Seems to have been stable for quite a while now.
