### ISSUE TITLE
rewrite in a lang with a good discord library

### ISSUE THREAD

**Issue by eepykate** [unixporn/trup#119]
i think everyone has had enough of discordgo's shit by this point.

~~current candidate: rust, it's a popular lang and (apparently) serenity-rs is good. The maintainer, mlvzk, has already announced a desire to rewrite, and 3 people (including him) in the mod team know rust, as well as a regular member expressing a desire to help. (xerox'd from https://github.com/unixporn/trup/issues/119#issuecomment-708935605)~~

We haven't had many discordgo issues recently (So no real reason to rewrite), when/if we do the rewrite it'll likely be in rust.

**Comment by elkowar** [comment]
*in a proper lang with a good discord library
pls fix title

**Comment by eepykate** [comment]
@elkowar good langs don't have good discord libraries because they're usually not the most popular due to requiring more than half a brain to use.

comment\_(disambiguation):  
good langs aren't popular due to requiring more than half a brain  
not every person who uses a popular lang only has half a brain, they're just usable by someone with half a brain  
having a good discord lib and being a good lang aren't the same  
being a popular lang and having a good discord lib aren't the same (case in point: go)

**Comment by elkowar** [comment]
There are three viable Options here:
- Rust (-> Hard, code would definitely be more complex, discord library would probably not be 100% feature-complete but very unlikely to ever break or have issues)
- Kotlin (-> JVM has very good discord libraries, is a very stable and solid platform. Main issue here would be that a good development setup includes IntelliJ, which many first-time contributors wouldn't want to deal with)
- TypeScript (-> allegedly has one of the best libraries out there, and typescript is solid enough to at least be a solid improvement over go. Main issue here would still be the JS ecosystem and TS still not being a _good_ language)

My preference obviously is in favor of Kotlin, as it's the only language on the list that is simple, easy, _and_ good. Amount of possible contributors would likely still be lower than with TypeScript, although it is also likely that the people implementing that _do_ implement features in Kotlin would be able to make up for the reduced contributor count by just being able to implement features more easily and solidly. 

Rust would not be a good choice in my opinion, for the reasons stated in the list above, and for the main reason of not providing much benefit over Kotlin in the domain of a discord bot.

**Comment by elkowar** [comment]
Alternative 4 would be to get together a couple golang users and contribute some fixes to discordgo, thus not having to rewrite the bot at all. A rewrite brings a non-trivial amount of effort with it, which we should only do if there is no reasonable alternative.

**Comment by eepykate** [comment]
bruski i am all bark no bite, i'll complain all i want for a rewrite and not contribute a single line

:+1: looks good

**Comment by sophec** [comment]
I am particularly interested in Rust as an option, though it may not be the most viable one. It should have the same (or better, maybe, not sure) performance as go, which is good. The discord library I don't think is a huge issue; we have enough manpower that if there are issues with the library we can fix and PR, or just maintain a fork if necessary. I think the biggest benefit over Kotlin in particular is that I have seen far more Rust around than Kotlin and would wager we could get more support/involvement with the community with Rust than with Kotlin, but that's just my two cents. I don't know either well enough to work on the rewrite in either, but from what I do know, Rust seems like a more maintainable option in the long run despite being a bit more complex.

**Comment by sophec** [comment]
Oh, and elko's point about discordgo is reasonable, I would say a full rewrite is not worth the time and effort in any language if we can just make what we have now work better.

**Comment by elkowar** [comment]
You do have a point regarding amount of possible contributors being more in rust. The big issue I take in doing this with rust is that rust does add quite a bit of complexity in terms of implementation. Performance is irrelevant, and jvm definitely performs as good as go fwiw here, so that shouldn't matter. Maintainability, stability and development fun should be the top and probably only priorities here.
Rust definitely wins in stability, but the other two are very hard to judge - although TS looses in all of them.

Maintainability for us also depends on developer availability of course, and that's where is see the key issue you're pointing out: with kotlin, I'd likely be the main / only maintainer and dev for a good while. It's not as popular in the bubble of Unix enthusiasts.

Rewriting trup with the explicit goal of just PRing to libs if we need to is a bad Idea imo, as a rewrite would already be quite the effort on its own. Rusts viability thus mainly depends on the available libs and the amount of work we could put in to writing clean abstractions over the complexity rust introduces to keep maintainability optimal.

**Comment by clbx** [comment]
write it in assembly you casuals

**Comment by eepykate** [comment]
how hard would networking be in asm anyway?

**Comment by elkowar** [comment]
After looking at serenity-rs, I think a rust bot might actually be the perfect choice. Seems to be high level yet flexible enough to do everything we need (and much more) without having to deal with a lot of the complexity of rust getting in the way. Rust has thus definitely won over TS completely for me, and I think it would likely be the best choice (mainly because I wouldn't want to be the sole maintainer of a kotlin bot :P)

**Comment by eepykate** [comment]
The sole maintainer? More like the sole contributor.

**Comment by elkowar** [comment]
Sadly, this. Cpli mentioned wanting to work on a rust rewrite, and @mlvzk already announced a desire to rewrite. Should probably be possible to get close to feature parity within a couple weekends, tbh...

At least 3 people in the mod team knowing and liking Rust definitely speaks in its favor in this regard 👍

**Comment by ooctavian** [comment]
just hire someone to do everything trup does
Advantages :  
- don't need to code 
- easily add new features to the "bot"
- don't need to interact with any discord library 

_Don't take seriously what I've said_

**Comment by Jimmysit0** [comment]
I actually think that Discord.js is a good option, since it's probably the easiest and the most common, its docs has all the info you may need and more, and there are also a lot of tutorials out there, so why not? I think it will even give the bot a nicer vibe, since the one just feels boring and the only used command is !fetch, and with djs there are a lot of functions that you could add, well it's just my opinion and as the guy up me said "Don't take seriously what I've said"

Greetings

**Comment by sophec** [comment]
> just hire someone to do everything that trup does

@virginfuhrer He might be onto something :thinking:

> I actually think that Discord.js is a good option

@Jimmysit0 Having used discord.js, I cannot recommend against it any harder.

**Comment by elkowar** [comment]
generally, working on the bot should be fun (which is something that js already fails at quite hard, although not as badly as go). as long as the library we are using has all the basic functionality, there wont be anything we could do in discord js that we couldnt in serenity or probably even discordgo. the big issue with discordgo is that its broken in many ways, buggy as hell and pretty anoying to work with. 

I feel like we've pretty much decided on going with rust, which i think is the best decision we can make. easy is nice, but good is much nicer. serenity provides a very high level of abstraction that should make reimplementing everything we have in trup a breeze, and adding more stuff just as easy.

if you feel like trup is boring or lacking features, feel free to file issues with specific features you would like to see! @Jimmysit0

**Comment by Jimmysit0** [comment]
Which library are you gonna use? (just asking)

**Comment by elkowar** [comment]
serenity-rs, by the looks of it

**Comment by chxp82q** [comment]
@elkowar You won't be the sole maintainer of the bot if its in kotlin, I will help :+1:  (or try to)

**Comment by eepykate** [comment]
good ol kotlin cafe

**Comment by radiohertz** [comment]
I'd like to help if you decide to go with Rust.

**Comment by elkowar** [comment]
A few more details on the plan: in a couple weeks we (by that I currently mean buffet, mlvzk and me) will  try to get as much as possible done within a weekend of coding, probably just hanging out in VC for the whole day. That way, we'll be able to quickly get the codebase far enough to have all the structure work done, and just require reimplementing the features that we didn't get to during that time.

As soon as the basics are done, any contributions will be more than welcome, as it's gonna be a lot of simple busywork to reimplement trups featureset.

**Comment by elkowar** [comment]
While we're at it I'll also strongly suggest that we migrate from postgres to Sqlite, as setting that up as well as managing backups etc is much more convenient with sqlite for a small scale project like this. What are your thoughts on this, @mlvzk ? (given that u originally made the decision to use postgres for trup)? Also, how hard would the database migration from postgres to sqlite be?

**Comment by mlvzk** [comment]
Backups are not a problem and they're already set up in a nice(and cheap) way. If we continue to store large blobs in the database then it won't be any easier than backing up postgres.
I don't know if sqlite has all the features that we need, but if it does then the convenience of setting up a dev environment would be very nice.

Maybe we could have an in-memory database abstraction for people that just wanna `cargo run`?

**Comment by elkowar** [comment]
sounds like a good idea, but i'm not familar enough with the DB ecosystem in rust to say if it's viable. afaik SQLite should be enough, except maybe the file storage (which we could easily do on the filesystem too, without any complications)

i guess we'll figure that out once we start working on it :D

**Comment by davidnoronha1** [comment]
Discord.js is very well documented with examples while serenity is still working on it sort of
Ive tried both for making an extendible discord bot but serentity and rust couldnt do it probably for good reasons, but I managed to get it to work in typescript

**Comment by safinsingh** [comment]
Keep in mind that it may be harder get others to help once the initial stuff has been completed... async Rust is a different paradigm that requires more knowledge than just Rust basics. I'd go with TypeScript here because the Discord library is simply phenomenal, the typings are great, and the docs are awesome. It'd be a lot easier for new contributors to hop on because JavaScript is fairly easy to pick up and it's portability means that a lot of people know it from other things already. As for performance, I really don't think there would be a hugely noticeable difference... As a note, this depends on how much you care about contributors after scaffolding, which I believe you should consider.

**Comment by eepykate** [comment]
I wonder how many features have been delayed due to this being (seemingly) endlessly put off.

**Comment by heavyrain266** [comment]
I think for that purpose TypeScript wirh Akairo will enough, this framework removes all manually implemeted shit like commands and listeners handlers etc. It makes everything faster and easier to setup.

**Comment by eepykate** [comment]
I'm fairly certain that it's already been decided that we're going to do
rust, but there haven't been many issues with trup recently and everyone
planning to work on it has been busy, so there's no real reason to do it.
I think some people have said there isn't really a good reason to switch
from one bad lang (go) to another (typescript), and we might as well go all
out on a good lang.

**Comment by safinsingh** [comment]
@6gk, in your opinion, why is TypeScript bad?

**Comment by safinsingh** [comment]
@branwright1 Discord.js is by far the most complete and heavily maintained Discord library for JavaScript that exists.

**Comment by eepykate** [comment]
I used "I think some people have said" specifically to avoid that question.

**Comment by eepykate** [comment]
I have no right to decide what lang this will be, since I don't plan to work on the rewrite anyway.  

And I think @elkowar was the one that said typescript bad, and he's probably the smartest person here lol.

**Comment by elkowar** [comment]
Typescript isn't _bad_, it just also isnt good. Thing is that one of the reasons Trup isnt just some premade bot is that its, well, fun to maintain our own bot. Doing this in an ecosystem that the main maintainers actively enjoy working in naturally makes a lot of sense. Serenity seems moredthan adequate both in completeness and solidity, thus id be surprised if the library would become an issue in any way similar to how it did with discordgo. 

But yea, it seems that currently there isnt any concrete _need_ for a rewrite, and noone has the motivation/time to do it, so its probably not gonna happen soon, id guess.

**Comment by sophec** [comment]
@elkowar just start writing it in Rust and let everyone adapt. It will take you like 45 minutes to write the whole thing in Rust, since I'm sure you'll just use 340 crates and use 20 lines of code, each with 40 separate function calls. Just rip the band-aid off.

**Comment by chxp82q** [comment]
yes and it will take an hour to build and check each time (tis a joke elko pls no elkograph of y it takes time ik already)

**Comment by eepykate** [comment]
@JavaCafe01 idk sounds fine to me

**Comment by eepykate** [comment]
just make sure there's no linter plz

**Comment by davidnoronha1** [comment]
> And I think @elkowar was the one that said typescript bad, and he's probably the smartest person here lol.

You have a point there

**Comment by safinsingh** [comment]
joke's on you @6gk, clippy is a rustup component so most people already have it already lol. most of the time it just provides syntactic suggestions anyway, the compiler doesn't let you write bad code.

**Comment by eepykate** [comment]
@safinsingh

> the compiler doesn't let you write bad code.

Sure, mate.  
Whining about the syntax won't fix using the completely wrong method of achieving a goal.

**Comment by eepykate** [comment]
> you havent written literally any rust code ever you dont know the feeling

get rekt nerd, use a good lang.

also if it does more than whining about syntax and actually whines about you using the wrong method i'd argue the compiler is going way beyond its scope.

**Comment by davidnoronha1** [comment]
A good lang like go? Go's compiler doesn't complain much 😅

**Comment by eepykate** [comment]
"good lang" excludes go

I was thinking more on the lines of C  (aka based lang).

**Comment by davidnoronha1** [comment]
Why not go all out and do it in x86 assembly as someone suggested

**Comment by eepykate** [comment]
@safinsingh

hoes mad

hoes mad

can't write C code, hoes mad

~~fwiw C wasn't a bot lang suggestion~~

**Comment by safinsingh** [comment]
gk you've never written c or any actual code ever 😩

**Comment by eepykate** [comment]
did you not know that @willeccles is in fact my alt?

**Comment by davidnoronha1** [comment]
Now that is interesting

**Comment by sophec** [comment]
It's true, I am @6gk's alt.

**Comment by ghost** [comment]
well pythons has a good python libary

**Comment by mlvzk** [comment]
There haven't been any active efforts in rewriting, therefore it must prove that Go is the superior language for writing discord bots. Closing.

**Comment by elkowar** [comment]
big Ooph, but you are correct in that the bot has been stable enough not to really _require_ a rewrite currently. My internship ends soon, so maybe i'll have more time for sideprojects in the near future, in which case I might finally start the rewrite - but no hurry or anything so closing this for now is sensible (especially given that it's not had productive discussion for many months, pretty much repeating the same "why not python" comments 🤷🏻‍♂️ )

**Comment by eepykate** [comment]
omg are you becoming the CEO of Porsche now??
