### ISSUE TITLE
Dynamic role list

### ISSUE THREAD

**Issue by eepykate** [unixporn/trup#139]
Every role below (and including) [ID] should be self-assignable.  
This should be checked whenever the bot starts (including !restart)

Example role list:
```
mute
black [this ID is in the var]
red
yellow
...
pink
```

**Comment by Tanish2002** [comment]
Do we have black?

**Comment by eepykate** [comment]
no, it was an example

**Comment by eepykate** [comment]
closed as "not really needed"
