### ISSUE TITLE
Make trup send a PSA about repetitive posts whenever someone posts in #server-feedback

### ISSUE THREAD

**Issue by mlvzk** [unixporn/trup#156]
![image](https://user-images.githubusercontent.com/44906333/106734449-51ef9680-6613-11eb-8cf2-eb2d3f52c090.png)

**Comment by mlvzk** [comment]
![image](https://user-images.githubusercontent.com/44906333/106736230-7a789000-6615-11eb-8e04-da4390d6daf6.png)

**Comment by davidv171** [comment]
Thoughts? 
![image](https://user-images.githubusercontent.com/26347830/106743431-a9dfca80-661e-11eb-8690-2f019afd63ca.png)

**Comment by eepykate** [comment]
So to be clear,

Whenever a new post is in #server-feedback, trup will mention the user in #bot (or DM them? I don't know if there's a way to check if DMs failed using the API) saying something along the lines of

> `@user` Please check if your post is a repetitive topic, for a list of repetitive topics check the pins of #server-feedback .
> If your post is a part of the list, it's recommended you delete it.

And then whenever a topic becomes "repetitive" a mod can write a "PSA" in a format similar to (below) then pin it

> > Replace heart react with up/downvotes

> The heart react in #showcase used to be thumbs up/down, but it was changed due to being mildly toxic, If you want to tell someone their setup is bad, elaborate on it and give them tips on how to improve, just disliking their post accomplishes nothing.

---

> > Add distro/wm/pronoun/etc roles

> Distro/WM roles would just be duplicated information, as !fetch exists.  As well as cluttering the role list, they can also make an *easy* (clicking user is easier & more tempting than running fetch) basis for ad hominem during arguments.  (ex: you use ubuntu? no wonder you're bad.)
> Pronoun roles aren't really relevant to the server, you can easily add them to your nickname / status.  Not to mention, after a while of being in the server active people generally know your pronouns of choice.  We don't tolerate bigotry so if someone keeps intentionally misgendering you *after being told*, feel free to mention/PM a mod.

**Comment by eepykate** [comment]
For what it's worth, I don't think having a single pin for disallowed topics is a good idea.  2k characters might sound like a lot, but it's really not.  My last comment was 1.5k characters, and that only covered 2 topics + a few unrelated sentences.

Also it would bring less attention to new additions, as well as having to ask the poster to edit it in.

**Comment by eepykate** [comment]
> I think the idea of having a "always-at-the-bottom" message by trup that reminds people to check the search for their topic, and of the rules for feedback could help a lot. like, not even the stupidest person in the world would post "music bot plox" when the last message in the channel was literally "check the history" and the history says "no music bot fuck you"

​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ - elkowar

This sounds decent (of course the older no-longer-bottom messages would be automatically rm'd)

---

to clarify "always on bottom": Someone posts, trup's old message gets deleted, trup reposts their message so it's always at the bottom

ex:
```
[james] we should add X
[trup]  *that PSA* (deleted)
[liam]  hmm, i'd really like Y
[trup]  *that PSA*
```

I would assume it acts like
1. checks db for old message ID
2. deletes it
3. posts
4. saves that message ID to db

**Comment by eepykate** [comment]
As others have said, a big issue here is the wording on trup's message.  We have to make it clear that we don't want repetitive feedback (shown in pins) while at the same time not making them scared to post anything.

**Comment by elkowar** [comment]
This has now been merged, and can thus be closed!
