### ISSUE TITLE
rewrite in rust

### ISSUE THREAD

**Issue by mlvzk** [unixporn/trup#17]
Not sure how mature serenity is and if it can do all what we need, but should be viable
for talking with database we could use diesel.rs

**Comment by tteeoo** [comment]
Not to be rude, and Rust is a good language, but... why?

**Comment by aosync** [comment]
I think that Rust would allow the project to ascend to perfection more easily and more rapidly and would give an occasion to each contributor to englighten themselves `( ͡° ͜ʖ ͡°)`

**Comment by buffet** [comment]
Is this still something to consider? Trup is mostly "done" and I don't see much reason to rewrite it at this point.

**Comment by elkowar** [comment]
I agree. eventhough go is definitely not a good language, rewriting in rust would
- not really benefit the main developers that much, as trup is already mostly done
- make it a lot harder for inexperienced people to contribute, and thus would not, imo, even be a good idea.

The only rewrite that _might_ make sense would be typescript, but again, there is no real point to doing a rewrite at this point.

**Comment by eepykate** [comment]
DiscordGo has a state bug thing, which makes users duplicate after being open for a while. (#38, #39)
