### ISSUE TITLE
announce mute start/end and warns in #modlog

### ISSUE THREAD

**Issue by mlvzk** [unixporn/trup#19]

**Comment by davidv171** [comment]
What is the message template? I can add this over the weekend

**Comment by mlvzk** [comment]
@davidv171 

Mute start:
`User <@id> was muted for <time> with reason: <reason>`

Mute end:
`User <@id> is now unmuted.`

Warn:
`User <@id> was warned by moderator <moderator.Username> with reason <reason>. This is their <nth> warning.`

They will all go to the #modlog channel, for which we need a new CHANNEL_MODLOG variable.

**Comment by davidv171** [comment]
Proposing to change:
> Their nth warning 
With:
> Warning number n
To avoid complexity of 3rd/first/second/fourth etc.
