### ISSUE TITLE
Make matching on multiple members interactive, fix matching generally

### ISSUE THREAD

**Issue by davidv171** [unixporn/trup#39]
example:

User: `!fetch david`

Trup: 
```
error: matched more than one user, which one did you mean?
1: davidv7#4226
2: davidlee#5195
3: david#5710
```
After this, the user inputs the index number of the target user, and trup fetches for him.

So in the case of the user inputting `1`, the `davidv7#4226` user would be fetched.

There have been some bug reports of matching reporting false multiple hits:

![image](https://user-images.githubusercontent.com/26347830/86362982-6bdc8b80-bc76-11ea-8152-717f66e2e087.png)

A similar user command working correctly:

![image](https://user-images.githubusercontent.com/26347830/86363125-af36fa00-bc76-11ea-938d-8d3a825f15fe.png)

Thanks to @GaugeK for the report.

EDIT: The bug report is already documented in #38

**Comment by elkowar** [comment]
iirc, @wooosh had started work on this, but never finished it. how far did you get with it / did you already have something working? this should just be implemented at some point, a general interactive member search mechanism would be very nice to have

**Comment by mlvzk** [comment]
Solved in https://github.com/unixporn/trup/pull/87
