### ISSUE TITLE
Make users choose role by name.

### ISSUE THREAD

**Issue by SpicyForthProgrammer** [unixporn/trup#61]
Roles should be displayed as their name instead of as a number for convenience.

**Comment by eepykate** [comment]
For convenience? Sir, typing 2-5 extra characters is not my idea of convenient.

**Comment by buffet** [comment]
Typing !role to get the number for each role isn't convenient either though. Also it's not really obvious that you're supposed to use numbers (even though it says so).

**Comment by eepykate** [comment]
I agree, do the first 1/2 letters of each colour (Make everything after optional), and either nothing or `l`/`list` for listing.

`!r y` for yellow, as an example.

**Comment by Tanish2002** [comment]
I'll try to do this
