### ISSUE TITLE
trup's fetch

### ISSUE THREAD

**Issue by dnl32** [unixporn/trup#67]
create trup's fetch, so you could run !fetch @Trup and see what software/hardware he uses. that doesn't really do anything useful but it will be a cool easter egg in my opinion.

**Comment by clbx** [comment]
~~Trup runs on a Poweredge 2970 with 2 6 Core Opteron Processors and 32GB of RAM.~~

~~The VM has much less than that though.~~

not anymore

**Comment by buffet** [comment]
Done.
