### ISSUE TITLE
Split log channels

### ISSUE THREAD

**Issue by buffet** [unixporn/trup#71]
The proposed split:

- #mod-commands is #bot-shit (channel to issue commands in) (trup doesn't have to be aware of this)
- #mod-cases logs !ban !warn !mute
- #mod-automod logs automatic message removal (with reason and message)
- #mod-messages logs user deletion and edits
- #mod-traffic logs people joining and leaving

The reasoning behind this proposal is that mods can mute some things, but not others, without having to make a decision for all of them combined.

**Comment by elkowar** [comment]
So:
- Bot-shit stays botshit
- ModLog stays modlog
- BotLog get's split up into AutoMod, BotMessages & BotTraffic (<- i've renamed mod-messages and mod-traffic to bot-messages and bot-traffic here, as i think that makes more sense)

does that sound good?

**Comment by buffet** [comment]
Yeah, that sounds good.
