### ISSUE TITLE
Mute gets slower over time

### ISSUE THREAD

**Issue by buffet** [unixporn/trup#77]
The longer trup is running the longer it takes for the mute command to take effect.

Might be related to the state issues in discordgo.

**Comment by eepykate** [comment]
also it repeats the "user unmuted" message a few times, not really a set amount though.

**Comment by eepykate** [comment]
apparently the delay happens with `!role` too? according to wosh.

**Comment by buffet** [comment]
@6gk This seems to be resolved, no?

**Comment by eepykate** [comment]
yep, looks like it.

**Comment by eepykate** [comment]
FWIW the bot's uptime is 8 days, which is the longest we've had so far.
