### ISSUE TITLE
!ban should DM the user with the reason before banning them, to make it more clear why they were banned

### ISSUE THREAD

**Issue by buffet** [unixporn/trup#93]
Actually Discord should do this but eh.

**Comment by eepykate** [comment]
Sure.

It must include something in the vein of "Do not contact mods asking to be unbanned, you won't be" though.

**Comment by buffet** [comment]
I feel like it shouldn't, mods also make mistakes.

**Comment by eepykate** [comment]
Eh, we do, but that's human nature.

However, too many people DM / go to another server to complain to mods
about getting banned/muted. Even when it was justified.

**Comment by buffet** [comment]
I feel like that will actually get **less** when people know why they've been banned.

Maybe also more descriptive ban reasosn then?

**Comment by eepykate** [comment]
> I feel like that will actually get less when people know why they've been banned.

Actually, that's a good point.

**Comment by davidv171** [comment]
Does the reason not automatically get DM'd or displayed to the banned user? What's the current behavior?

**Comment by eepykate** [comment]
@davidv171 It's just silent. It disappears from your server list and you can't rejoin, you don't even get told the reason, however it's in the audit log and banned user list
