### ISSUE TITLE
/dev/null is empty

### ISSUE THREAD

**Issue by sophec** [unixporn/trup#94]
this is bad

if anyone except @buffet closes this issue i will literally do ***nothing*** with extreme prejudice >:(

**Comment by eepykate** [comment]
hmm, this is weird.

Have you tried putting anything in it? Try ***__FEED THE VOID__***

    dd if=/dev/urandom of=/dev/null

**Comment by buffet** [comment]
I just checked locally, and I'm shocked, it's indeed empty.

However I ran some diagnostics over at HQ, and it seems like everything is working fine, so this might not be an issue.

I'd suggest closing this for now, maybe reopen if we actually encounter any problems.

**Comment by eepykate** [comment]
> However I ran some diagnostics over at HQ, and it seems like everything is working fine, so this might not be an issue.

That is odd. Why would a file being empty be "intended"??

**Comment by sophec** [comment]
Well, he didn't say it was intended. It may have been unintentional, but unimportant.

**Comment by eepykate** [comment]
True that!
