### ISSUE TITLE
Send autodeleted messages in DMs to the user

### ISSUE THREAD

**Issue by emilydaemon** [unixporn/trup#97]
Some people have been typing out long, long paragraphs about some things that have contained some words some people don't like, and they have been autodeleted by trup. However, because of the way it works now, you cannot edit out the words and resend it. For example, sending the message "foobar" gets deleted by trup, and then trup sends a message like "Please do not say 'foo' in r/unixporn. Your message: foobar" to the user who originally posted the message in DMs.

**Comment by mlvzk** [comment]
Good idea

**Comment by Tanish2002** [comment]
I'll try to do this
